In [31]:
import math
from random import seed
from random import randint
import numpy as np                    #Para trabajar con matrices
from binarytree import tree, build    #Para trabajar con árboles

#Función para generar arreglos de enteros para tests
def generarRandomArr(a, b, size):   #Rango [a,b]
    arr = []
    for _ in range(size):
        valor = randint(a, b)
        arr.append(valor)
    return arr

## Práctica

#### Ejercicio 1
Escriba un algoritmo con dividir y conquistar que determine si un arreglo de tamaño potencia de 2 es *más
a la izquierda*, donde "más a la izquierda" significa que:
La suma de los elementos de la mitad izquierda superan los de la mitad derecha.
- Cada una de las mitades es a su vez "más a la izquierda".
- Por ejemplo, el arreglo \[8, 6, 7, 4, 5, 1, 3, 2\] es "más a la izquierda", pero \[8, 4, 7, 6, 5, 1, 3, 2\] no lo es.

Intente que su solución aproveche la técnica de modo que la complejidad del algoritmo sea estrictamente menor a O(n<sup>2</sup>).

In [2]:
#Solución
def masALaIzq(A):        #Devuelve una tupla (res: bool, sumaizq: int, sumader: int)
    if len(A) == 2:
        if A[0] > A[1]:
            return (True, A[0], A[1])
        else:
            return (False, A[0], A[1])
    
    R1 = masALaIzq(A[0:len(A)//2])          #T(n/2)
    R2 = masALaIzq(A[len(A)//2:len(A)])     #T(n/2)
    sumaR1 = R1[1] + R1[2]
    sumaR2 = R2[1] + R2[2]
    
    return (R1[0] and R2[0] and sumaR1 > sumaR2, sumaR1, sumaR2)

In [3]:
#Tests
A = [8, 6, 7, 4, 5, 1, 3, 2]    #Resultado esperado: True
print("Resultado test 1: ", masALaIzq(A))

B = [8, 4, 7, 6, 5, 1, 3, 2]    #Resultado esperado: False
print("Resultado test 2: ", masALaIzq(B))

C = [2, 10, 9, 6, 9, 9, 5, 6]   #Resultado esperado: False
print("Resultado test 3: ", masALaIzq(C))

D = [10, 2, 6, 5]               #Resultado esperado: True
print("Resultado test 4: ", masALaIzq(D))

Resultado test 1:  (True, 25, 11)
Resultado test 2:  (False, 25, 11)
Resultado test 3:  (False, 27, 29)
Resultado test 4:  (True, 12, 11)


**Complejidad**: La recurrencia es de la forma T(n) = 2 T(n/2) + O(1). Por el Teorema Maestro, la complejidad es O(n).

#### Ejercicio 2
Tenemos un arreglo a = \[a<sub>1</sub>, a<sub>2</sub>, ..., a<sub>n</sub>\] de n enteros distintos (positivos y negativos) en orden estrictamente creciente. Queremos determinar si existe una posición i tal que a<sub>i</sub> = i. Por ejemplo, dado el arreglo A = \[-4, -1, 2, 4, 7\], i = 4 es esa posición.
Diseñar un algoritmo dividir y conquistar eficiente (de complejidad de orden estrictamente menor que lineal) que resuelva el problema. Calcule y justifique la complejidad del algoritmo dado.

**Aclaración**: en el ejemplo, la primera posición del arreglo es i = 1. Aquí se considerará que la primera posición es i = 0 y, por lo tanto, el resultado esperado del ejemplo de arriba sería *False*.

In [4]:
#Solución
def buscarIndIgualContenido(A, posInicial):   #Devuelve bool
    if len(A) == 1:
        return A[0] == posInicial
    
    m = len(A)//2
    if A[m] < m + posInicial:
        return buscarIndIgualContenido(A[m:len(A)], m + posInicial)
    elif A[m] > m + posInicial:
        return buscarIndIgualContenido(A[0:m], 0 + posInicial)
    else:
        return True

In [5]:
#Tests
A = [-4, -1, 2, 4, 7]    #Resultado esperado: True
print("Resultado test 1: ", buscarIndIgualContenido(A, 0))

B = [-4, -1, 4, 5, 7, 8]    #Resultado esperado: False
print("Resultado test 2: ", buscarIndIgualContenido(B, 0))

C = [-1, 0, 1, 2, 3, 5]    #Resultado esperado: True
print("Resultado test 3: ", buscarIndIgualContenido(C, 0))

D = [0, 2, 3, 4, 7, 8]    #Resultado esperado: True
print("Resultado test 4: ", buscarIndIgualContenido(D, 0))

Resultado test 1:  True
Resultado test 2:  False
Resultado test 3:  True
Resultado test 4:  True


**Complejidad**: La recurrencia es de la forma T(n) = T(n/2) + O(1). Por el Teorema Maestro, la complejidad es O(log n).

#### Ejercicio 3
Encuentre un algoritmo para calcular a<sup>b</sup> en tiempo logarítmico en b. Piense cómo reutilizar los resultados ya calculados. Justifique la complejidad del algoritmo dado.

In [6]:
#Solución
def potencia(b, p):
    if p == 0:
        return 1
    elif p == 1:
        return b
    
    r = potencia(b, p//2)    #T(p/2)
    if p % 2 == 0:
        return r*r
    else:
        return b*r*r

In [7]:
#Tests
print("3^3 = ", potencia(3, 3))
print("2^5 = ", potencia(2, 5))
print("5^0 = ", potencia(5, 0))
print("5^1 = ", potencia(5, 1))
print("5^3 = ", potencia(5, 3))

3^3 =  27
2^5 =  32
5^0 =  1
5^1 =  5
5^3 =  125


**Complejidad**: La recurrencia es de la forma T(p) = T(p/2) + O(1). Por el Teorema Maestro, la complejidad es O(log p).

#### Ejercicio 5
Suponga que se tiene un método *potencia* que, dada un matriz cuadrada A de orden 4 × 4 y un número *n*,
computa la matriz A<sup>n</sup>. Dada una matriz cuadrada A de orden 4 × 4 y un número natural *n* que es potencia de 2 (i.e., n = 2<sup>k</sup> para algun k ≥ 1), desarrollar, utilizando la técnica de dividir y conquistar y el método *potencia*, un algoritmo que permita calcular A<sup>1</sup> + A<sup>2</sup> + ... + A<sup>n</sup>.
Calcule el número de veces que el algoritmo propuesto aplica el método *potencia*. Si no es estrictamente menor que O(n), resuelva el ejercicio nuevamente.

**Idea:**
F(1) = A </br>
F(2) = A + A² = A(I + A) </br>
F(4) = A + A² + A³ + A⁴ = (A + A²)(I + A²) = A(I + A)(I + A²) = F(2)(I + A²) </br>
Forma general: F(n) = F(n/2)*(I + A^(n/2)) </br>
(Tomada de https://stackoverflow.com/questions/18890570/matrix-power-sum)

In [32]:
#Solución
def sumaPotenciasMatriz(A, n):
    if n == 1:
        return A
    if n == 2:      
        return np.add(A, np.linalg.matrix_power(A, 2))  #np.linalg.matrix_power(A, n) es el método potencia
                                                        #np.add y np.matmul son suma y producto de matrices respectivamente
    I = [[1, 0, 0, 0],     # matriz identidad
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1]]
    I = np.array(I)
    S = np.add(I, np.linalg.matrix_power(A, n//2))      #Suma matriz identidad + potencia n/2
    return np.matmul(sumaPotenciasMatriz(A, n//2), S)   #T(n/2)

In [33]:
#Tests
A = [[1, 0, 0, 1],
     [2, 0, 1, 2],
     [-1, 1, 0, 2],
     [0, 1, 2, 1]]
A = np.array(A)
A2 = np.linalg.matrix_power(A, 2)
A3 = np.linalg.matrix_power(A, 3)
A4 = np.linalg.matrix_power(A, 4)
sum1 = np.add(A, A2)
sum2 = np.add(A3, A4)
print("Resultado esperado:\n", np.add(sum1, sum2))
print("Resultado:\n", sumaPotenciasMatriz(A, 4))

Resultado esperado:
 [[  7  19  29  40]
 [ 14  49  72 103]
 [  8  37  57  73]
 [  9  50  70 103]]
Resultado:
 [[  7  19  29  40]
 [ 14  49  72 103]
 [  8  37  57  73]
 [  9  50  70 103]]


**Complejidad**: La recurrencia tiene la forma T(n) = T(n/2) + O(1), donde n es la cantidad de veces que se aplica el método *potencia*. Por el Teorema Maestro, la complejidad es O(log n).

#### Ejercicio 6
Dado un árbol binario cualquiera, diseñar un algoritmo de dividir y conquistar que devuelva la máxima distancia entre dos nodos (es decir, máxima cantidad de ejes a atravesar). El algoritmo no debe hacer recorridos innecesarios sobre el árbol.

In [54]:
#Solución
def maxDistanciaSubarb(A):
    if A == None:
        return 0
    if A.left == None and A.right == None:
        return 1

    return 1 + max(maxDistanciaSubarb(A.left), maxDistanciaSubarb(A.right))

def maxDistancia(A):
    return 1 + maxDistanciaSubarb(A.left) + maxDistanciaSubarb(A.right)

In [61]:
#Tests
valuesA = [1,2,3,4,5,6]
A = build(valuesA)
print(A)
print("Resultado test 1:", maxDistancia(A))
                                        
B = tree(is_perfect=False)
print(B)
print("Resultado test 2:", maxDistancia(B))


    __1__
   /     \
  2       3
 / \     /
4   5   6

Resultado test 1: 5

  _____8__
 /        \
13         9___
  \       /    \
   6     2     _14
    \         /   \
     4       11    5

Resultado test 2: 7


#### Ejercicio 7
La cantidad de parejas en desorden de un arreglo A\[1...n\] es la cantidad de parejas de posiciones 1 ≤ i <
j ≤ n tales que A\[i\] > A\[j\]. Dar un algoritmo que calcule la cantidad de parejas en desorden de un arreglo
y cuya complejidad temporal sea estrictamente mejor que O(n<sup>2</sup>) en el peor caso.

**Hint**: Considerar hacer una modificación de un algoritmo de sorting.

## Ejercicios de parcial

### 1) Divide & Conquer sobre arreglos

#### 1er cuatrimestre 2017 (Parcial)

Una empresa informa todos los días el cierre de sus ganancias netas (que pueden ser negativas si tuvo
pérdida ese día). Dado un arreglo con tales montos para un período de n días consecutivos, el directorio de la
empresa necesita conocer en qué intervalo de días (dentro de este período) se obtuvo la mayor ganancia (la
ganancia en un intervalo de días es la suma de los montos informados en los días dentro de ese intervalo).
Usando la técnica de D&C, dar un algoritmo que tome un arreglo con los montos de n días consecutivos (i.e., los días de 0 a n−1) e indique un intervalo de días \[i, j\], con 0 ≤ i ≤ j < n, en el cual se maximiza la suma de tales montos (puede asumirse que n > 0). El algoritmo propuesto debe tener complejidad estrictamente menor que O(n<sup>2</sup>), lo cual debe justificarse adecuadamente.

***Ayuda***: Si pidiésemos que el intervalo devuelto contenga sí o sí un determinado día k, entonces el problema
se resuelve en tiempo O(n) (¡pensar cómo!). Aprvechar ese procedimiento en el algoritmo global de D&C
implementado.

In [10]:
#Solución
def periodoMaxGananciaCentro(A, posInicial):  # Devuelve una tupla: (inicio: nat, fin: nat, ganancia: nat)
    if len(A) == 2:
        return (posInicial + 0, posInicial + 1, A[0] + A[1])
    
    sumaActual = A[len(A)//2]                 # mayor hacia derecha
    sumaMaxDer = A[len(A)//2]
    indiceFin = len(A)//2
    for i in range(len(A)//2+1,len(A)): 
        sumaActual = sumaActual + A[i]
        if sumaActual > sumaMaxDer:
            sumaMaxDer = sumaActual
            indiceFin = i
    
    sumaActual = A[len(A)//2]                 # mayor hacia izquierda
    sumaMaxIzq = A[len(A)//2]
    indiceInicio = len(A)//2
    i = len(A)//2-1
    while i >= 0:
        sumaActual = sumaActual + A[i]
        if sumaActual > sumaMaxIzq:
            sumaMaxIzq = sumaActual
            indiceInicio = i
        i-=1
    
    return (indiceInicio + posInicial, indiceFin + posInicial, sumaMaxIzq + sumaMaxDer - A[len(A)//2])

def periodoMaxGanancia(A, posInicial):   # Devuelve una tupla: (inicio: nat, fin: nat, ganancia: nat)
    if len(A) == 1:
        return (posInicial + 0, posInicial + 0, A[0])
    
    p1 = periodoMaxGanancia(A[0:len(A)//2], posInicial)                   #T(n/2)
    p2 = periodoMaxGanancia(A[len(A)//2:len(A)], len(A)//2 + posInicial)  #T(n/2)
    p3 = periodoMaxGananciaCentro(A, posInicial)                          #O(n)
    
    res = p1
    if p2[2] > res[2]:
        res = p2
    if p3[2] > res[2]:
        res = p3
    return res

In [11]:
#Tests
test1 = [-13, 15, -2, -1, 5, 18, 18, -19, 14, -5]   #Resultado esperado: (1, 6, 53)
test2 = [27, 20, -40, 23, 5]                        #Resultado esperado: (0, 1, 47)
test3 = [16, 17, 25, -5, 3, -3, 24, 10]             #Resultado esperado: (0, 7, 87)
rndmtest1 = generarRandomArr(-20, 20, 10)
rndmtest2 = generarRandomArr(-50, 50, 5)
rndmtest3 = generarRandomArr(-5, 25, 8)

print("Caso de test 1: ", test1)
print("Resultado test 1: ", periodoMaxGanancia(test1, 0), "\n")

print("Caso de test 2: ", test2)
print("Resultado test 2: ", periodoMaxGanancia(test2, 0), "\n")

print("Caso de test 3: ", test3)
print("Resultado test 3: ", periodoMaxGanancia(test3, 0), "\n")

print("Caso de random test 1: ", rndmtest1)
print("Resultado random test 1: ", periodoMaxGanancia(rndmtest1, 0),"\n")

print("Caso de random test 2: ", rndmtest2)
print("Resultado random test 2: ", periodoMaxGanancia(rndmtest2, 0), "\n")

print("Caso de random test 3: ", rndmtest3)
print("Resultado random test 3: ", periodoMaxGanancia(rndmtest3, 0), "\n")

Caso de test 1:  [-13, 15, -2, -1, 5, 18, 18, -19, 14, -5]
Resultado test 1:  (1, 6, 53) 

Caso de test 2:  [27, 20, -40, 23, 5]
Resultado test 2:  (0, 1, 47) 

Caso de test 3:  [16, 17, 25, -5, 3, -3, 24, 10]
Resultado test 3:  (0, 7, 87) 

Caso de random test 1:  [-11, 11, -1, -1, -4, 1, -1, 13, -3, -4]
Resultado random test 1:  (1, 7, 18) 

Caso de random test 2:  [-33, -8, -15, 36, -39]
Resultado random test 2:  (3, 3, 36) 

Caso de random test 3:  [10, 17, 16, 10, 17, 4, 12, 6]
Resultado random test 3:  (0, 7, 92) 



**Complejidad**: la recurrencia tiene la forma T(n) = 2 T(n/2) + O(n). <br />
a = 2, c = 2, log2 (2) = 1 <br /> 
Por el teorema maestro (2do caso), la complejidad del algoritmo es O(n log n).

#### 1er cuatrimestre 2017 (Recuperatorio)

Se tiene un arreglo de naturales sin repeticiones que estaba ordenado pero al cual se lo rotó circularmente k
posiciones a la derecha. Por ejemplo, \[10, 13, 1, 4, 6, 7, 8\] fue rotado k = 2 veces mientras que \[6, 7, 8, 10, 13, 1, 4\] fue rotado 5 veces. Escribir un algoritmo que reciba uno de estos arreglos y devuelva el máximo elemento en
tiempo estrictamente menor que O(*n*). Justifique la correctitud del algoritmo y su complejidad temporal.

In [12]:
#Solución
def maxArrRotado(arr):
    if len(arr) == 1:
        return arr[0]                    #O(1)
    elif len(arr) == 2:
        return max(arr[0], arr[1])       #O(1)
    m = len(arr)//2
    if arr[0] > arr[m]:
        return maxArrRotado(arr[0:m])  #T(n/2)
    else:
        return maxArrRotado(arr[m:len(arr)])

In [13]:
#Tests
test1 = [10, 13, 1, 4, 6, 7, 8]
test2 = [6, 7, 8, 10, 12, 1, 4] 
test3 = [1, 4, 6, 7, 8, 10, 12]

print("Caso de test 1: ", test1)
print("Resultado test 1: ", maxArrRotado(test1), "\n")

print("Caso de test 2: ", test2)
print("Resultado test 2: ", maxArrRotado(test2), "\n")

print("Caso de test 3: ", test3)
print("Resultado test 3: ", maxArrRotado(test3), "\n")

Caso de test 1:  [10, 13, 1, 4, 6, 7, 8]
Resultado test 1:  13 

Caso de test 2:  [6, 7, 8, 10, 12, 1, 4]
Resultado test 2:  12 

Caso de test 3:  [1, 4, 6, 7, 8, 10, 12]
Resultado test 3:  12 



**Complejidad**: la recurrencia tiene la forma T(n) = T(n/2) + O(1). <br />
a = 1, c = 2, log2(1) = 0 <br /> 
Por el teorema maestro (2do caso), la complejidad del algoritmo es O(log n).

#### 2do cuatrimestre 2018 (Recuperatorio)
Un arreglo de enteros es de a lo sumo uno distinto si a lo sumo un elemento del arreglo es distinto del resto.
Por ejemplo los arreglos \[1, 1, 1\], \[1, 2, 1, 1, 1\] y \[5, 71\] son de a lo sumo uno distinto pero los arreglos \[1, 2, 1, 2, 2\] y \[1, 2, 3\] no lo son.
Se pide diseñar un algoritmo de Divide & Conquer que, dado un arreglo cualquiera, devuelva la longitud del subarreglo (de elementos contiguos) más largo que sea a lo sumo uno distinto. Por ejemplo, dado el arreglo \[5, 1, 1, 2, 1, 7\] la respuesta del algoritmo debería ser 4 (la longitud del subarreglo \[1, 1, 2, 1\]). El algoritmo debe tener una complejidad temporal estrictamente menor que O(n²). La complejidad del algoritmo debe estar correctamente justificada.

In [14]:
#Solución
def maxUnoDistintoCentro(arr):
    maxCen = 1
    m = len(arr)//2
    i = m-1
    while i >= 0 and arr[i] == arr[m]:
        maxCen +=1
        i-=1
    j = m+1
    while j < len(arr) and arr[j] == arr[m]:
        maxCen +=1
        j+=1
    #i es el índice del primero que es dif a izq, j es el índice del primero que es dif a der
    if maxCen > 1:
        difIzq = i
        maxIzq = 1
        if i != -1:
            i-=1
            while i >= 0 and arr[i] == arr[m]:
                maxIzq+=1
                i-=1
        difDer = j
        maxDer = 1
        if j != len(arr):
            j+=1
            while j < len(arr) and arr[j] == arr[m]:
                maxDer+=1
                j+=1
        maxCen = maxCen + max(maxIzq, maxDer)
    if maxCen == 1:
        izq = i
        maxIzq = 1
        if i != -1:
            i-=1
            while i >= 0 and arr[i] == arr[izq]:
                maxIzq+=1
                i-=1
        der = j
        maxDer = 1
        if j != len(arr):
            j+=1
            while j < len(arr) and arr[j] == arr[der]:
                maxDer+=1
                j+=1
        if izq >= 0 and der < len(arr) and arr[izq] == arr[der]:
            maxCen = maxCen + maxIzq + maxDer
        else:
            maxCen = maxCen + max(maxIzq, maxDer)

    return maxCen

def maxUnoDistinto(arr):
    if len(arr) == 1:
        return 1
    if len(arr) == 2:
        return 2
    r1 = maxUnoDistinto(arr[0:len(arr)//2])            #T(n/2)
    r2 = maxUnoDistinto(arr[len(arr)//2:len(arr)])     #T(n/2)
    r3 = maxUnoDistintoCentro(arr)                       #O(n)
    return max(max(r1, r2), r3)

In [15]:
#Tests
test1 = [5, 1, 1, 2, 1, 7]
test2 = [5, 1, 3, 2, 1]
test3 = [5, 1, 1, 1, 2, 7]
rndmtest1 = generarRandomArr(0, 8, 10)
rndmtest2 = generarRandomArr(1, 5, 5)
rndmtest3 = generarRandomArr(2, 4, 8)

print("Caso de test 1: ", test1)
print("Resultado test 1: ", maxUnoDistinto(test1), "\n")

print("Caso de test 2: ", test2)
print("Resultado test 2: ", maxUnoDistinto(test2), "\n")

print("Caso de test 3: ", test3)
print("Resultado test 3: ", maxUnoDistinto(test3), "\n")

print("Caso de random test 1: ", rndmtest1)
print("Resultado random test 1: ", maxUnoDistinto(rndmtest1),"\n")

print("Caso de random test 2: ", rndmtest2)
print("Resultado random test 2: ", maxUnoDistinto(rndmtest2), "\n")

print("Caso de random test 3: ", rndmtest3)
print("Resultado random test 3: ", maxUnoDistinto(rndmtest3), "\n")

Caso de test 1:  [5, 1, 1, 2, 1, 7]
Resultado test 1:  4 

Caso de test 2:  [5, 1, 3, 2, 1]
Resultado test 2:  2 

Caso de test 3:  [5, 1, 1, 1, 2, 7]
Resultado test 3:  4 

Caso de random test 1:  [2, 2, 6, 4, 8, 3, 4, 4, 5, 0]
Resultado random test 1:  3 

Caso de random test 2:  [4, 2, 4, 5, 2]
Resultado random test 2:  2 

Caso de random test 3:  [2, 4, 3, 4, 2, 2, 3, 2]
Resultado random test 3:  4 



**Complejidad**: la recurrencia tiene la forma T(n) = 2 T(n/2) + O(n). <br />
a = 2, c = 2, log2 (2) = 1 <br /> 
Por el teorema maestro (2do caso), la complejidad del algoritmo es O(n log n).

### 2) Divide & Conquer sobre matrices

#### 2do cuatrimestre 2015 (Parcial)
El famoso y archiconocido juego ***3mb0l3*** se juega, como todos saben, sobre un tablero cuadrado de lado n con n = 2k para algún k natural. El tablero está dividido en n × n casillas. Participan dos jugadores, cada uno tiene su identificador **B** o **N**. En algunas casillas del tablero, un jugador colocó su identicador. Puede haber casillas vacías y no hay más de un identicador por casilla. Una vez finalizado el juego, para decidir el ganador se consideran k + 1 niveles distintos, numerados de 0 a k. El nivel i se forma dividiendo el cuadrado original en 2^(k−i) × 2^(k-i) casillas. Así, el nivel k consta de una sola casilla, el k −1 de un tablero de 2 × 2 y así siguiendo. Se puede ver en la gura cómo quedan los distintos niveles. Para cada casilla de cada nivel (salvo el 0), se toma como dueño de la misma al jugador que más casillas controla del nivel anterior teniendo en cuenta solamente las que están contenidas en la casilla grande. Se coloca el identicador del dueño en cada casilla, y en caso de empate se coloca una **E**. Para cada nivel, se toma como ganador del nivel al que más casillas controla de ese nivel. Acá nuevamente puede haber empate. Por último se dice que el ganador del juego es aquel que haya ganado mayor cantidad de niveles. Realizar un algoritmo que dado un tablero, con los dueños de cada casillero en el nivel 0, devuelva si gana **B** o **N** todo el juego, o **E** si hay empate.
Se pide dar un algoritmo que utilice la técnica de Dividir y Conquitar y además se debe calcular y justicar su complejidad temporal.
En el ejemplo de la figura, se tiene un tablero con n = 2^2, por lo que hay niveles de 0 a 2. Por ejemplo, en el nivel 1 la casilla inferior izquierda es controlada por **B**, pues entre las casillas correspondientes en el nivel 0 hay tres **B** y una **N**. El nivel 0 es empate pues hay igual cantidad de casillas controladas por cada jugador, el nivel 1 lo gana **B** pues hay dos **B** y sólo una **N** y el nivel 2 lo gana **B**. Como **B** ganó dos niveles y **N** ninguno, el algoritmo debe dar **B** como respuesta.
<center>
<img src="D&C_pics/tablero.jpg" alt="drawing" width="200" /> <br/>
    </center>

In [16]:
#Solución
def construirSigNivel(A):    # Devuelve una matriz que corresponde al nivel siguiente a A
    if len(A) == 2:
        contE = 0
        contB = 0
        contN = 0
        for i in range(0,len(A)):
            for j in range(0,len(A)):
                if A[i][j] == 'E':
                    contE += 1
                elif A[i][j] == 'B':
                    contB += 1
                else:
                    contN +=1
        if contB > contN:
            return [['B']]
        elif contN > contB:
            return [['N']]
        else:
            return [['E']]
        
    n = len(A)
    A = np.array(A)
    g1 = construirSigNivel(A[0:n//2,0:n//2])            #T(n/4)
    g2 = construirSigNivel(A[0:len(A)//2,n//2:n])       #T(n/4)
    g3 = construirSigNivel(A[n//2:n,0:n//2])            #T(n/4)
    g4 = construirSigNivel(A[n//2:n,n//2:n])            #T(n/4)
    
    G1 = np.concatenate((g1, g2), axis=1)
    G2 = np.concatenate((g3,g4),  axis=1)
    G = np.concatenate((G1, G2), axis=0)
    return G                                                       #Complejidad total: O(n^2)

def jugar3mb013(A, k):     #Toma un tablero y un nivel y devuelve el ganador hasta ese nivel
    puntN = 0
    puntB = 0
    nivel = 0
    while nivel <= k:                           #k*
        A = np.array(A)
        T = construirSigNivel(A)                 #O(n^2)
        resJ = jugar3mb013(T, nivel)             #O(n)
        if resJ[0] > resJ[1]:
            puntN+=1
        elif resJ[1] > resS[0]:
            puntB+=1
        nivel+=1
    if puntN < puntB:
        return 'B'
    elif puntB < puntN:
        return 'N'
    else:
        return 'E'

def calcularGanador(A):       #Devuelve una tupla <N: nat, B: nat> con la cantidad de N y de B
    if len(A) == 1:
        if A[0][0] == 'N':
            return (1,0)
        elif A[0][0] == 'B':
            return (0,1)
        else:
            return (0,0)
    
    ultNivel = int(math.log(len(A),2))
    print(ultNivel)
    n = len(A)
    A = np.array(A)
    g1 = jugar3mb013(A[0:n//2,0:n//2], ultNivel-1)         #T(n/4)
    g2 = jugar3mb013(A[0:n//2,n//2:n], ultNivel-1)         #T(n/4)
    g3 = jugar3mb013(A[n//2:n,0:n//2], ultNivel-1)         #T(n/4)
    g4 = jugar3mb013(A[n//2:n,n//2:n], ultNivel-1)         #T(n/4)
    
    puntN = g1[0] + g2[0] + g3[0] + g4[0]
    puntB = g1[1] + g2[1] + g3[1] + g4[1]
    
    if puntN < puntB:
        return (0, 1)
    elif puntB < puntN:
        return (1, 0)
    else:
        return (0, 0)

#Complejidad: 4 T(n/4) + O(1) -> O(n)

In [17]:
#Tests
A = [['N', 'N', 'B', 'B'],
     ['N', 'N', 'N', 'N'],
     ['B', 'B', 'B', 'B'],
     ['N', 'B', 'B', 'N']]

A = np.array(A)
B = [['N', 'N', 'B', 'B', 'N', 'B', 'B', 'B'],
     ['N', 'N', 'N', 'N', 'B', 'N', 'B', 'N'],
     ['B', 'B', 'B', 'B', 'N', 'N', 'N', 'N'],
     ['N', 'B', 'B', 'N', 'N', 'B', 'B', 'B'],
     ['B', 'N', 'B', 'N', 'B', 'N', 'B', 'N'],
     ['N', 'N', 'N', 'B', 'B', 'B', 'N', 'N'],
     ['B', 'B', 'N', 'N', 'B', 'N', 'B', 'N'],
     ['N', 'B', 'N', 'B', 'B', 'N', 'N', 'B']]
B = np.array(B)
print(jugar3mb013(A[0:len(A)//2,0:len(A)//2], 1))
print(construirSigNivel(B))

RecursionError: maximum recursion depth exceeded while calling a Python object

#### 2do cuatrimestre 2019 (Parcial)
COMPLETAR

In [ ]:
#Solución
def buscarHueco(A, fi, ci):  #fi = fila de inicio, ci = columna de inicio
    if len(A) == 2:                        #casos base
        if A[0][0]+1 != A[1][0]:
            return (1 + fi, 0 + ci)
        elif A[0][0]+1 != A[0][1]:
            return (0 + fi, 1 + ci)
        elif A[0][0]+2 != A[1][1]:
            return (1 + fi, 1 + ci)
        else:
            return (0, 0)
        
    n = len(A)
    if A[0][n//2] != A[0][n//2-1]+1:    #casos en los que el hueco está al comienzo de una submatriz
        return (0 + fi, n//2 + ci)
    elif A[n//2][0] != A[n//2-1][0]+1:
        return (n//2 + fi, 0 + ci)
    elif A[n//2][n//2] != A[n//2-1][n//2]+1:
        return (n//2 + fi, n//2 + fi)
        
    if (A[n//2-1][n//2-1] - A[0][0]) != 2*(n//2-1):    #casos recursivos
        return buscarHueco(A[0:n//2,0:n//2], 0 + fi, 0 + ci)         #T(n/4)
    elif (A[n//2-1][n-1] - A[0][n//2]) != 2*(n//2-1):
        return buscarHueco(A[0:n//2,n//2:n], 0 + fi, n//2 + ci)      #T(n/4)   
    elif (A[n-1][n//2-1] - A[n//2][0]) != 2*(n//2-1):
        return buscarHueco(A[n//2:n,0:n//2], n//2 + fi, 0 + ci)      #T(n/4)
    elif (A[n//2][n//2] - A[n-1][n-1]) != 2*(n//2-1):
        return buscarHueco(A[n//2:n,n//2:n], n//2 + fi, n//2 + ci)   #T(n/4)

In [ ]:
#Tests
A = [[1, 2, 3, 4],    #Respuesta esperada: (1,1) (caso normal)
     [2, 4, 5, 6],
     [3, 5, 6, 7],
     [4, 6, 7, 8]]
A = np.array(A)

B = [[1, 2, 3, 4],    #Respuesta esperada: (2,2) (hueco al comienzo de submatriz)
     [2, 3, 4, 5],
     [3, 4, 6, 7],
     [4, 5, 7, 8]]
B = np.array(B)

C = [[1, 2, 3, 4],    #Respuesta esperada: (0,0) (sin hueco)
     [2, 3, 4, 5],
     [3, 4, 5, 6],
     [4, 5, 6, 7]]
C = np.array(C)

D = [[1, 2, 3, 4],    #Respuesta esperada: (1,3) (hueco en columna)
     [2, 3, 4, 6],
     [3, 4, 5, 7],
     [4, 5, 6, 8]]
D = np.array(D)

E = [[1, 2, 3, 4, 5, 6, 7, 8],         #Respuesta esperada: (5,6)
     [2, 3, 4, 5, 6, 7, 8, 9],
     [3, 4, 5, 6, 7, 8, 9, 10],
     [4, 5, 6, 7, 8, 9, 10, 11],
     [5, 6, 7, 8, 9, 10, 11, 12],
     [6, 7, 8, 9, 10, 11, 13, 14],
     [7, 8, 9, 10, 11, 12, 14, 15],
     [8, 9, 10, 11, 12, 13, 15, 16]]
E = np.array(E)

print("Resultado test 1: ", buscarHueco(A, 0, 0))
print("Resultado test 2: ", buscarHueco(B, 0, 0))
print("Resultado test 3: ", buscarHueco(C, 0, 0))
print("Resultado test 4: ", buscarHueco(D, 0, 0))
print("Resultado test 5: ", buscarHueco(E, 0, 0))

**Complejidad**: La recurrencia es de la forma T(n) = T(n/4) + O(1).

### 3) Divide & Conquer sobre árboles

#### 1er Cuatrimestre 2018 (Parcial)
La copa de un árbol binario de naturales está formada por los primeros niveles (completos) del árbol cuyos elementos coincidan con el de la raíz. Por ejemplo, el siguiente ́arbol tiene una copa de tamaño 2 (formada por el nodo raíz y sus dos hijos), aunque si el nodo marcado en gris tuviese un 5 en lugar de un 4, el ́arbol tendría una copa de tamaño 3. <br/>
<center>
<img src="D&C_pics/copamaxima.jpg" alt="drawing" width="400" /> <br/>
    </center>
Se pide diseñar un algoritmo de tipo Divide & Conquer que dado un ́arbol binario de naturales, indique el tamaño máximo de copa entre todos los subárboles del mismo (consideramos que un árbol es también subárbol de sí mismo). En el ejemplo anterior, la respuesta sería 3, dada por el subárbol izquierdo de la raíz del árbol (cuya copa de tamaño 3 está enmarcada en el triángulo). El algoritmo diseñado debe tener una complejidad de peor caso de O(n), siendo n la cantidad de nodos del arbol. Se pide además:
<br/> 1. Justificar la complejidad del algoritmo suponiendo que el árbol está balanceado.
<br/> 2. Justificar la complejiad del algoritmo en el caso en que el árbol no esté balanceado.

In [ ]:
#Solución
def copaMaxima(A):
    if A.left == None or A.right == None:
        return 1
    resIzq = copaMaxima(A.left)
    resDer = copaMaxima(A.right)
    if A.value == (A.right).value and A.value == (A.left).value:
        if resDer == resIzq:
            return resDer + 1
    return max(resDer, resIzq)

In [ ]:
#Tests
valuesA = [5,5,5,5,5,4,5,5,5,5,5,3,1,3,2]
A = build(valuesA)
print(A)
print("Resultado test 1:", copaMaxima(A))
valuesB = [5,5,4,5,5,5,5,5,5,3,1,3,2,1]
B = build(valuesB)
print(B)
print("Resultado test 2:", copaMaxima(B))
valuesC = generarRandomArr(1,6,8)
C = build(valuesC)
print(C)
print("Resultado random test 1:", copaMaxima(C))

**Complejidad**: </br>
1. Si el árbol está balanceado, se puede usar el Teorema Maestro. La recurrencia es de la forma T(n) = 2 T(n/2) + O(1) -> O(n)
2. Si el árbol no está balanceado, se puede usar un árbol de recursión. La complejidad también es O(n) porque se pasa por cada nodo una única vez.

#### 2do cuatrimestre 2018 (Parcial)
Decimos que un  ́arbol binario de booleanos esta equilibrado si para todo nodo del arbol ocurre que la cantidad
de falsos en su subarbol izquierdo difiere en a lo sumo uno con la cantidad de verdaderos en su subarbol derecho.
Sabiendo que contamos con las operaciones de  ́arbol binario *nil*?, *raiz*, *izq* y *der*, cuyas complejidades temporales son O(1), proponer un algoritmo que utilice la técnica de Dividir y Conquistar para determinar si un arbol binario de booleanos esta equilibrado. El algoritmo propuesto debe tener complejidad O(n), donde n es la cantidad de nodos del arbol, sin importar si el mismo esta o no balanceado (notar que estar equilibrado no implica estar balanceado ni viceversa). La complejidad del algoritmo debe estar correctamente justificada.

In [ ]:
#Solución
def arboolEquilibrado(A):
    #print(A.value)             #Habilitar para ver complejidad (qué nodos recorre y cuántas veces)
    if A.left == None and A.right == None:
        if A.value == False:
            return (True, 1)    #Equilibrado?, #Falsos
        else:
            return (True, 0)
    fraiz = 0
    if A.value == False:
        fraiz = 1
    subIzq = arboolEquilibrado(A.left)
    subDer = arboolEquilibrado(A.right)
    return (subIzq[0] and subDer[0] and abs(subIzq[1] - subDer[1]) < 2, subIzq[1] + subDer[1] + fraiz)

In [ ]:
#Tests
valuesA = [True, False, False, False, False]
A = build(valuesA)
print(A)
print(arboolEquilibrado(A))
valuesB = [True, False, False, True, False]
B = build(valuesB)
print(B)
print(arboolEquilibrado(B))

**Complejidad**: O(n), donde n es la cantidad de nodos del árbol, ya que se recorre cada nodo una única vez. Se puede mostrar con un árbol de recursión (ver comentario en función).